config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications'
  end
  mount API => '/'
  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords:'users/passwords',
    omniauth_callbacks:'users/omniauth_callbacks'
  }
  root to: "welcomes#index"
  get 'user/root' => "welcomes#index"

  resources :articles, only: [:show,:index]
  resources :categories, only: [:index,:show]

  resources :products,only:[:index] do 
    collection do 
      post :vote
    end
  end

  resources :users, only: [:show,:update,:index]
  mount Sidekiq::Web => '/sidekiq'

  namespace :admin do
    resources :categories
    resources :images
    resources :articles do 
      collection do 
        post :preview
      end
      member do 
        get :publish
      end
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId

  include A

  friendly_id :name, use: :slugged
  validates :name, presence: true, uniqueness: true
  validates :content, presence: true
  
  belongs_to :category, counter_cache: true
  belongs_to :user
  before_save :fill_html_content
  before_destroy :delete_hits_cache_key

  scope :default_order, -> { order("created_at DESC") }
  scope :publish, -> {where("publish_state = ?",1)}

  def get_user
    self.user.try(:nick_name) || self.user.try(:email)
  end

  def self.hits_sort
    article_hash = Hash.new
    Article.publish.each do |article|
      article_hash.merge!({ article.id => article.hits})
    end
    article_arr = article_hash.sort do |a,b|
      b[1] <=> a[1]
    end
    article_ids = article_arr.map { |article| article[0] }
    if article_ids.present?
      Article.where("id in (:ids)",:ids=> article_ids).order("FIELD(id,#{article_ids.join(',')})")
    else
      Article.where(id: [])
    end
  end

  def hits
    cache_key = self.hits_cache_key
    $redis.get(cache_key).to_i
  end

  def incr_hits
    cache_key = self.hits_cache_key
    $redis.incr(cache_key)
  end

  def delete_hits_cache_key
    $redis.del(hits_cache_key)
  end

  def hits_cache_key
    ["hits",self.id,self.created_at.to_i].join("_")
  end

  private

  def fill_html_content
    self.content_html = MyMarkdown.render(self.content)
  end


end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::AdminController
  layout 'application'
  before_action :set_article,only:[:show,:edit,:update,:destroy,:publish]

  def index
    @articles = Article.includes(:user,:category).default_order.page(params[:page])
  end

  def show
  end

  def publish
    @article.publish_state = 1
    if @article.save
      redirect_to admin_articles_path
    else
      redirect_to admin_articles_path, notice: I18n.t("admin.articles.index.publish_issue")
    end
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to admin_articles_path
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to admin_articles_path
    else
      render 'edit' 
    end
  end

  def destroy
    @article.destroy
    redirect_to admin_articles_path,notice: '文章成功删除!'
  end

  def preview
    content = params[:content]
    html_content = MyMarkdown.render(content)
    render json:{html_content: html_content}
  end

  private 
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:name,:content,:user_id,:category_id)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  layout 'application'
  def show
    @article = Article.friendly.find(params[:id])
    @article.incr_hits
    render 'admin/articles/show'
  end

  def index
    if params[:search].present?
      search = params[:search]
      @articles = Article.where("name like ? or content like ?","%#{search}%","%#{search}%").default_order.page(params[:page])
      @article_count = @articles.count
    else
      @articles = Article.default_order.page(params[:page])
      @article_count = Rails.cache.fetch("articles_count",expires_in: 5.minutes) do 
        Article.count
      end
    end
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/views/admin/articles/_form.html.erb
<%= bootstrap_form_for([:admin,@article]) do |f| %>
  <%= f.error_messages %>
  <%= f.text_field :name,class:"form-control"%>
  <%= f.select :category_id, Category.all.collect { |p| [ p.name, p.id ] },{},class:"form-control"%>
  <%= f.text_area :content,rows: 25,class:"form-control" %>
  <% if @article.new_record?%>
    <%= f.hidden_field :user_id, value: current_user.id%>
  <% else %>
    <%= f.hidden_field :user_id, value: @article.user_id%>
  <% end %>
  <%= f.submit t('.save'),class: 'btn btn-primary' %>
<% end %>

<button class='btn btn-primary article_preview' id="preview"  data-toggle="modal" data-target="#markdown_modal"><%=t('.preview')%></button>

<div class="modal fade" id="markdown_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog article_preivew_modal">
    <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h2 class="modal-title article_preview_title" id="preview_title"><%=t('.preview_content')%></h2>
      </div>
      <div class="modal-body" id="preview_content">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%=t('.close')%></button>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $('#markdown_modal').on('show.bs.modal', function () {
    var article_content = $("#article_content").val();
    var title_content = $("#article_name").val();
    $.ajax({
      type:"post",
      dataType:"json",
      data:{content: article_content},
      url: "<%=preview_admin_articles_path%>",
      success:function(data){
        console.log(data.html_contentt)
        $("#preview_content").html(data.html_content);
        $("#preview_title").text(title_content);
      }
    })
  })
</script>

app/views/admin/articles/edit.html.erb
<div class="col-sm-offset-5">
  <h2><%=t('.title')%></h2>
</div>
<%= render 'form' %>

app/views/admin/articles/index.html.erb
<h2 class="col-sm-offset-5">
  <span><%=t('.title')%><span>
</h2>
<div class="container">
  <p><%= link_to t('.add'), new_admin_article_path, class: ' btn btn-success'%></p>
  <% if @articles.present? %>
    <div class = "panel panel-default">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>id</th>
            <th>title</th>
            <th>category</th>
            <th>author</th>
            <th>publish</th>
            <th>readcount</th>
            <th><%=t('.operate')%></th>
          </tr>
        </thead>
        <tbody>
          <% @articles.each do |article|%>
            <tr>
              <td class="col-sm-1"><%=article.id%></td>
              <td class="col-sm-2"><%=link_to article.name, admin_article_path(article)%></td>
              <td class="col-sm-2"><%=article.category.name%></td>
              <td class="col-sm-2"><%=article.get_user%></td>
              <td class="col-sm-2"><%=article.publish_state == 1 ? t(".publish") : t(".unpublish")%></td>
              <td class="col-sm-1"><%=article.hits%></td>
              <td class="col-sm-2">
              <% if can? :update, article %>
                <%= link_to t('.edit'),edit_admin_article_path(article)%>|
              <% end %>
              <% if can? :destroy,article%>
                <%= link_to t('.delete'), admin_article_path(article), method: :delete, data: { confirm: t('.delete_confirm') }%> |
              <% end %>
              <% if (can? :publish,article) && (article.publish_state.to_s == "0") %>
                <%= link_to t(".publish"),publish_admin_article_path(article)%>
              <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @articles %>
  <% else %>
    <div class="col-sm-offset-2">
      <h2><%=t('.blank')%></h2>
    </div>
  <% end %>
</div>

app/views/admin/articles/new.html.erb
<div class="col-sm-offset-5">
  <h2><%=t('.title')%></h2>
</div>
<%= render 'form' %>

app/views/admin/articles/show.html.erb
<h2 class="article_title"><%=@article.name%></h2>
<p class="pull-right">
  <span>
    <%= @article.user.try(:nick_name) || @article.user.try(:email)%>
    <%=t('.created_at1')%>
    <%=custome_time_ago(@article.created_at)%>
    <%=@article.hits%><%=t(".hits",:default => "hits")%>
  </span>
</p>
<% cache @article do%>
  <div class="row">
    <div class="col-md-10 col-sm-offset-1">
      <%=raw @article.content_html%>
    </div>
  </div>
<% end %>