config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications'
  end
  mount API => '/'
  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords:'users/passwords',
    omniauth_callbacks:'users/omniauth_callbacks'
  }
  root to: "welcomes#index"
  get 'user/root' => "welcomes#index"

  resources :articles, only: [:show,:index]
  resources :categories, only: [:index,:show]

  resources :products,only:[:index] do 
    collection do 
      post :vote
    end
  end

  resources :users, only: [:show,:update,:index]
  mount Sidekiq::Web => '/sidekiq'

  namespace :admin do
    resources :categories
    resources :images
    resources :articles do 
      collection do 
        post :preview
      end
      member do 
        get :publish
      end
    end
  end
end

app/views/shared/_flash_messages.html.erb
<% if flash.any?%>
  <div id="flash-messages">
    <% if flash[:notice]%>
      <div class="alert alert-info alert-autocloseable-info text-center">
        <a class="close" data-dismiss='alert'>x</a>
        <%= flash[:notice]%>
      </div>
    <% end %>
    <% if flash[:success]%>
      <div class="alert alert-success alert-autocloseable-success text-center">
        <a class="close" data-dismiss='alert'>x</a>
        <%= flash[:success]%>
      </div>
    <% end %>
    <% if flash[:warning]%>
      <div class="alert alert-warning alert-autocloseable-warning text-center">
        <a class="close" data-dismiss='alert'>x</a>
        <%= flash[:warning]%>
      </div>
    <% end %>
    <% if flash[:danger]%>
      <div class="alert alert-danger alert-autocloseable-danger text-center">
        <a class="close" data-dismiss='alert'>x</a>
        <%= flash[:danger]%>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<nav class="navbar-default footer">
  <div class="footer_info">
    <p><%=t(".my_blog")%></p>
    <p><%=link_to t(".code"),"https://github.com/zhangmingju/dongfeng"%></p>
  </div>
</nav>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="header_login">
      <div class="navbar-header">
        <%=link_to t(".logo"), root_path,class:"navbar-brand" %>
      </div>
      <div>
        <% if user_signed_in?%>
          <ul class="nav navbar-nav">
            <li><%=link_to t(".category"), admin_categories_path %></li>
            <li><%=link_to t(".article"), admin_articles_path %></li>
            <!-- <li><%#=link_to t(".vote"), products_path %></li> -->
          </ul>
          <ul class="nav navbar-nav">
            <li><%=link_to t(".article_images"), admin_images_path %></li>
          </ul>
          <ul class="nav navbar-nav">
            <li>
              <%= form_tag articles_path,method: "get",class:"navbar-form",role:"search" do %>
                <div class="form-group">
                  <%= text_field_tag 'search',nil,placeholder:"请搜索标题或者内容",class:"form-control"%>
                </div>
              <% end %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <%=current_user.nick_name || current_user.email%>
                    <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%=link_to t(".user_center") , user_path(current_user)%></li>
                    <li><%=link_to t(".sign_out"),destroy_user_session_path, method: :delete%></li>
                  </ul>
              </li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav">
            <li><%=link_to t(".category"), categories_path %></li>
            <li><%=link_to t(".article"), articles_path %></li>
            <!-- <li><%#=link_to t(".vote"), products_path %></li> -->
          </ul>
          <ul class="nav navbar-nav">
            <li>
              <%= form_tag articles_path,method: "get",class:"navbar-form",role:"search" do %>
                <div class="form-group">
                  <%= text_field_tag 'search',nil,placeholder:"请搜索标题或者内容",class:"form-control"%>
                </div>
              <% end %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%=link_to t(".sign_in"), new_user_session_path%></li>
            <li><%=link_to t(".sign_up"), new_user_registration_path%></li>
          </ul>
        <% end %>
      </div>
    </div>
</nav>