config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications'
  end
  mount API => '/'
  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords:'users/passwords',
    omniauth_callbacks:'users/omniauth_callbacks'
  }
  root to: "welcomes#index"
  get 'user/root' => "welcomes#index"

  resources :articles, only: [:show,:index]
  resources :categories, only: [:index,:show]

  resources :products,only:[:index] do 
    collection do 
      post :vote
    end
  end

  resources :users, only: [:show,:update,:index]
  mount Sidekiq::Web => '/sidekiq'

  namespace :admin do
    resources :categories
    resources :images
    resources :articles do 
      collection do 
        post :preview
      end
      member do 
        get :publish
      end
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_one :image, as: :target
  has_many :articles
  validates :name, presence: true, uniqueness: true

  scope :default_order, -> { order("created_at DESC") }

  def image_url
    image_url = self.image.name.url if self.image.present?
    upload_path  = Rails.root.join("public").to_s
    if image_url.present? && File.exist?(upload_path + image_url)
      image_url
    else
      Image.default_image
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  layout 'application'
  before_action :set_category,only:[:edit,:update,:destroy]
  load_and_authorize_resource :only => [:new, :edit]

  def index
    @categories = Category.includes(:image).default_order
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    ActiveRecord::Base.transaction do 
      @category = Category.new(category_params)
      if @category.save
        ImageUtil.image_upload(params[:category][:image],"Category",@category.id) if params[:category][:image].present?
        redirect_to admin_categories_path
      else
        render 'new'
      end
    end
  end

  def update
    if @category.update(category_params)
      ImageUtil.image_upload(params[:category][:image],"Category",@category.id) if params[:category][:image].present?
      redirect_to admin_categories_path
    else
      render 'edit' 
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_path,notice: '分类成功删除!'
  end

  private 
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name,:desc)
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout 'application'
  def index
    @categories = Category.includes(:image)
  end
  def show
    @category = Category.friendly.find(params[:id])
    @articles = @category.articles.includes(:user).publish.default_order.page(params[:page])
  end
end

app/views/admin/categories/_form.html.erb
<%= bootstrap_form_for([:admin,@category]) do |f| %>
  <%= f.error_messages %>
  <%= f.text_field :name,class:"form-control"%>
  <%= f.text_field :desc,class:"form-control"%>
  <%= f.file_field :image,class:"form-control"%>
  <%= f.submit t('.save'),class:"btn btn-primary"%>
<% end %>

app/views/admin/categories/index.html.erb
<h2 class="col-sm-offset-5">
  <span><%=t('.title')%><span>
</h2>
<div class="container">
  <% if can? :create, Category %>
    <p><%= link_to  t('.add'), new_admin_category_path, class: ' btn btn-success'%></p>
  <% end %>
  <% if @categories.present? %>
    <div class = "panel panel-default">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>id</th>
            <th>title</th>
            <th>desc</th>
            <th>image</th>
            <th>count</th>
            <th><%=t('.operate')%></th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category|%>
            <tr>
              <td class="col-sm-2"><%=category.id%></td>
              <td class="col-sm-2"><%=link_to category.name, category_path(category)%></td>
              <td class="col-sm-2"><%=category.desc%></td>
              <td><%=image_tag category.image_url,size:"80x80"%></td>
              <td class="col-sm-2"><%=category.articles_count%></td>
              <td class="col-sm-2">
              <% if can? :update, category %>
                <%= link_to t('.edit'),edit_admin_category_path(category)%>|
              <% end %>
              <% if can? :destroy, category%>
                <%= link_to t('.delete'), admin_category_path(category), method: :delete, data: { confirm: t('.delete_confirm') }%> 
              <% end%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <div class="col-sm-offset-2">
      <h2><%=t('.blank')%></h2>
    </div>
  <% end %>
</div>