config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications'
  end
  mount API => '/'
  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords:'users/passwords',
    omniauth_callbacks:'users/omniauth_callbacks'
  }
  root to: "welcomes#index"
  get 'user/root' => "welcomes#index"

  resources :articles, only: [:show,:index]
  resources :categories, only: [:index,:show]

  resources :products,only:[:index] do 
    collection do 
      post :vote
    end
  end

  resources :users, only: [:show,:update,:index]
  mount Sidekiq::Web => '/sidekiq'

  namespace :admin do
    resources :categories
    resources :images
    resources :articles do 
      collection do 
        post :preview
      end
      member do 
        get :publish
      end
    end
  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :target, polymorphic: true
  mount_uploader :name, ImageUploader
  belongs_to :user

  scope :default_order, -> { order("created_at DESC") }
  scope :article_images, -> { where("target_type = ?", "Article") }

  def self.get_images(instance)
    image_urls = instance.images.map do |image|
      image.image.url
    end
  end

  def get_user
    self.user.try(:nick_name) || self.user.try(:email)
  end

  def self.default_image
    "/uploads/image/default.jpg"
  end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < ApplicationController
  layout 'application'
  before_action :set_image,only:[:edit,:update,:destroy]

  def index
    @images = Image.article_images.default_order.page(params[:page])
  end

  def show
  end

  def new
    @image = Image.new
  end

  def edit
  end

  def create
    @image = Image.new(image_params)
    @image.target_type = "Article"
    if @image.save
      redirect_to admin_images_path
    else
      render 'new'
    end
  end

  def update
    if @image.update(image_params)
      redirect_to admin_images_path
    else
      render 'edit' 
    end
  end

  def destroy
    @image.destroy
    redirect_to admin_images_path,notice: '图片成功删除!'
  end

  private 
    def set_image
      @image = Image.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:name,:user_id)
    end
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/views/admin/images/_form.html.erb
<%= bootstrap_form_for([:admin,@image]) do |f| %>
  <%= f.error_messages %>
  <%= f.file_field :name,class:"form-control"%>
  <% if @image.new_record?%>
    <%= f.hidden_field :user_id, value: current_user.id%>
  <% else %>
    <%= f.hidden_field :user_id, value: @image.user_id%>
  <% end %>
  <%= f.submit t('.save'),class:"btn btn-primary"%>
<% end %>

app/views/admin/images/edit.html.erb
<div class="col-sm-offset-3">
  <h2><%=t('.title')%></h2>
</div>
<%= render 'form' %>

app/views/admin/images/index.html.erb
<h2 class="col-sm-offset-5">
  <span><%=t('.title')%><span>
</h2>
<div class="container">
  <p><%= link_to  t('.add'), new_admin_image_path, class: ' btn btn-success'%></p>
  <% if @images.present? %>
    <div class = "panel panel-default">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>id</th>
            <th>url</th>
            <th>image</th>
            <th>author</th>
            <th><%=t('.operate')%></th>
          </tr>
        </thead>
        <tbody>
          <% @images.each do |image|%>
            <tr>
              <td class="col-sm-1"><%=image.id%></td>
              <td class="col-sm-2"><%=Settings.domain.url + image.name.url.to_s%></td>
              <td class="col-sm-2"><%=image_tag image.name.url.to_s,size:"80x80"%></td>
              <td class="col-sm-2"><%=image.get_user%></td>
              <td class="col-sm-2">
              <% if can? :update, image %>
                <%= link_to t('.edit'),edit_admin_image_path(image)%>|
              <% end %>
              <% if can? :destroy, image%>
                <%= link_to t('.delete'), admin_image_path(image), method: :delete, data: { confirm: t('.delete_confirm') }%> 
              <% end%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @images %>
  <% else %>
    <div class="col-sm-offset-2">
      <h2><%=t('.blank')%></h2>
    </div>
  <% end %>
</div>

app/views/admin/images/new.html.erb
<div class="col-sm-offset-3">
  <h2><%=t('.title')%></h2>
</div>
<%= render 'form' %>